/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as PprofRouteRouteImport } from './routes/pprof/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as PprofIndexRouteImport } from './routes/pprof/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as WorkspaceVirtualKeysRouteRouteImport } from './routes/workspace/virtual-keys/route'
import { Route as WorkspaceScimRouteRouteImport } from './routes/workspace/scim/route'
import { Route as WorkspaceRoutingRulesRouteRouteImport } from './routes/workspace/routing-rules/route'
import { Route as WorkspaceRbacRouteRouteImport } from './routes/workspace/rbac/route'
import { Route as WorkspaceProvidersRouteRouteImport } from './routes/workspace/providers/route'
import { Route as WorkspacePluginsRouteRouteImport } from './routes/workspace/plugins/route'
import { Route as WorkspacePiiRedactorRouteRouteImport } from './routes/workspace/pii-redactor/route'
import { Route as WorkspaceObservabilityRouteRouteImport } from './routes/workspace/observability/route'
import { Route as WorkspaceModelLimitsRouteRouteImport } from './routes/workspace/model-limits/route'
import { Route as WorkspaceMcpSettingsRouteRouteImport } from './routes/workspace/mcp-settings/route'
import { Route as WorkspaceMcpRegistryRouteRouteImport } from './routes/workspace/mcp-registry/route'
import { Route as WorkspaceLogsRouteRouteImport } from './routes/workspace/logs/route'
import { Route as WorkspaceGuardrailsRouteRouteImport } from './routes/workspace/guardrails/route'
import { Route as WorkspaceGovernanceRouteRouteImport } from './routes/workspace/governance/route'
import { Route as WorkspaceDashboardRouteRouteImport } from './routes/workspace/dashboard/route'
import { Route as WorkspaceCustomPricingRouteRouteImport } from './routes/workspace/custom-pricing/route'
import { Route as WorkspaceConfigRouteRouteImport } from './routes/workspace/config/route'
import { Route as WorkspaceClusterRouteRouteImport } from './routes/workspace/cluster/route'
import { Route as WorkspaceAuditLogsRouteRouteImport } from './routes/workspace/audit-logs/route'
import { Route as WorkspaceAdaptiveRoutingRouteRouteImport } from './routes/workspace/adaptive-routing/route'
import { Route as WorkspaceVirtualKeysIndexRouteImport } from './routes/workspace/virtual-keys/index'
import { Route as WorkspaceScimIndexRouteImport } from './routes/workspace/scim/index'
import { Route as WorkspaceRoutingRulesIndexRouteImport } from './routes/workspace/routing-rules/index'
import { Route as WorkspaceRbacIndexRouteImport } from './routes/workspace/rbac/index'
import { Route as WorkspaceProvidersIndexRouteImport } from './routes/workspace/providers/index'
import { Route as WorkspacePluginsIndexRouteImport } from './routes/workspace/plugins/index'
import { Route as WorkspacePiiRedactorIndexRouteImport } from './routes/workspace/pii-redactor/index'
import { Route as WorkspaceObservabilityIndexRouteImport } from './routes/workspace/observability/index'
import { Route as WorkspaceModelLimitsIndexRouteImport } from './routes/workspace/model-limits/index'
import { Route as WorkspaceModelCatalogIndexRouteImport } from './routes/workspace/model-catalog/index'
import { Route as WorkspaceMcpToolGroupsIndexRouteImport } from './routes/workspace/mcp-tool-groups/index'
import { Route as WorkspaceMcpSettingsIndexRouteImport } from './routes/workspace/mcp-settings/index'
import { Route as WorkspaceMcpRegistryIndexRouteImport } from './routes/workspace/mcp-registry/index'
import { Route as WorkspaceMcpLogsIndexRouteImport } from './routes/workspace/mcp-logs/index'
import { Route as WorkspaceMcpAuthConfigIndexRouteImport } from './routes/workspace/mcp-auth-config/index'
import { Route as WorkspaceLogsIndexRouteImport } from './routes/workspace/logs/index'
import { Route as WorkspaceGuardrailsIndexRouteImport } from './routes/workspace/guardrails/index'
import { Route as WorkspaceGovernanceIndexRouteImport } from './routes/workspace/governance/index'
import { Route as WorkspaceDocsIndexRouteImport } from './routes/workspace/docs/index'
import { Route as WorkspaceDashboardIndexRouteImport } from './routes/workspace/dashboard/index'
import { Route as WorkspaceCustomPricingIndexRouteImport } from './routes/workspace/custom-pricing/index'
import { Route as WorkspaceConfigIndexRouteImport } from './routes/workspace/config/index'
import { Route as WorkspaceClusterIndexRouteImport } from './routes/workspace/cluster/index'
import { Route as WorkspaceAuditLogsIndexRouteImport } from './routes/workspace/audit-logs/index'
import { Route as WorkspaceAlertChannelsIndexRouteImport } from './routes/workspace/alert-channels/index'
import { Route as WorkspaceAdaptiveRoutingIndexRouteImport } from './routes/workspace/adaptive-routing/index'
import { Route as WorkspaceLogsDashboardRouteRouteImport } from './routes/workspace/logs/dashboard/route'
import { Route as WorkspaceProvidersRoutingRulesIndexRouteImport } from './routes/workspace/providers/routing-rules/index'
import { Route as WorkspaceProvidersModelLimitsIndexRouteImport } from './routes/workspace/providers/model-limits/index'
import { Route as WorkspacePromptRepoPromptsIndexRouteImport } from './routes/workspace/prompt-repo/prompts/index'
import { Route as WorkspacePromptRepoDeploymentsIndexRouteImport } from './routes/workspace/prompt-repo/deployments/index'
import { Route as WorkspacePiiRedactorRulesIndexRouteImport } from './routes/workspace/pii-redactor/rules/index'
import { Route as WorkspacePiiRedactorProvidersIndexRouteImport } from './routes/workspace/pii-redactor/providers/index'
import { Route as WorkspaceLogsMcpLogsIndexRouteImport } from './routes/workspace/logs/mcp-logs/index'
import { Route as WorkspaceLogsDashboardIndexRouteImport } from './routes/workspace/logs/dashboard/index'
import { Route as WorkspaceLogsConnectorsIndexRouteImport } from './routes/workspace/logs/connectors/index'
import { Route as WorkspaceGuardrailsProvidersIndexRouteImport } from './routes/workspace/guardrails/providers/index'
import { Route as WorkspaceGuardrailsConfigurationIndexRouteImport } from './routes/workspace/guardrails/configuration/index'
import { Route as WorkspaceGovernanceVirtualKeysIndexRouteImport } from './routes/workspace/governance/virtual-keys/index'
import { Route as WorkspaceGovernanceUsersIndexRouteImport } from './routes/workspace/governance/users/index'
import { Route as WorkspaceGovernanceTeamsIndexRouteImport } from './routes/workspace/governance/teams/index'
import { Route as WorkspaceGovernanceRbacIndexRouteImport } from './routes/workspace/governance/rbac/index'
import { Route as WorkspaceGovernanceCustomersIndexRouteImport } from './routes/workspace/governance/customers/index'
import { Route as WorkspaceConfigSecurityIndexRouteImport } from './routes/workspace/config/security/index'
import { Route as WorkspaceConfigProxyIndexRouteImport } from './routes/workspace/config/proxy/index'
import { Route as WorkspaceConfigPricingConfigIndexRouteImport } from './routes/workspace/config/pricing-config/index'
import { Route as WorkspaceConfigPerformanceTuningIndexRouteImport } from './routes/workspace/config/performance-tuning/index'
import { Route as WorkspaceConfigObservabilityIndexRouteImport } from './routes/workspace/config/observability/index'
import { Route as WorkspaceConfigMcpGatewayIndexRouteImport } from './routes/workspace/config/mcp-gateway/index'
import { Route as WorkspaceConfigLoggingIndexRouteImport } from './routes/workspace/config/logging/index'
import { Route as WorkspaceConfigLargePayloadIndexRouteImport } from './routes/workspace/config/large-payload/index'
import { Route as WorkspaceConfigClientSettingsIndexRouteImport } from './routes/workspace/config/client-settings/index'
import { Route as WorkspaceConfigCachingIndexRouteImport } from './routes/workspace/config/caching/index'
import { Route as WorkspaceConfigApiKeysIndexRouteImport } from './routes/workspace/config/api-keys/index'

const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PprofRouteRoute = PprofRouteRouteImport.update({
  id: '/pprof',
  path: '/pprof',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const PprofIndexRoute = PprofIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PprofRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const WorkspaceVirtualKeysRouteRoute =
  WorkspaceVirtualKeysRouteRouteImport.update({
    id: '/virtual-keys',
    path: '/virtual-keys',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceScimRouteRoute = WorkspaceScimRouteRouteImport.update({
  id: '/scim',
  path: '/scim',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceRoutingRulesRouteRoute =
  WorkspaceRoutingRulesRouteRouteImport.update({
    id: '/routing-rules',
    path: '/routing-rules',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceRbacRouteRoute = WorkspaceRbacRouteRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceProvidersRouteRoute = WorkspaceProvidersRouteRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePluginsRouteRoute = WorkspacePluginsRouteRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePiiRedactorRouteRoute =
  WorkspacePiiRedactorRouteRouteImport.update({
    id: '/pii-redactor',
    path: '/pii-redactor',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceObservabilityRouteRoute =
  WorkspaceObservabilityRouteRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceModelLimitsRouteRoute =
  WorkspaceModelLimitsRouteRouteImport.update({
    id: '/model-limits',
    path: '/model-limits',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceMcpSettingsRouteRoute =
  WorkspaceMcpSettingsRouteRouteImport.update({
    id: '/mcp-settings',
    path: '/mcp-settings',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceMcpRegistryRouteRoute =
  WorkspaceMcpRegistryRouteRouteImport.update({
    id: '/mcp-registry',
    path: '/mcp-registry',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLogsRouteRoute = WorkspaceLogsRouteRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceGuardrailsRouteRoute =
  WorkspaceGuardrailsRouteRouteImport.update({
    id: '/guardrails',
    path: '/guardrails',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceGovernanceRouteRoute =
  WorkspaceGovernanceRouteRouteImport.update({
    id: '/governance',
    path: '/governance',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceDashboardRouteRoute = WorkspaceDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceCustomPricingRouteRoute =
  WorkspaceCustomPricingRouteRouteImport.update({
    id: '/custom-pricing',
    path: '/custom-pricing',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceConfigRouteRoute = WorkspaceConfigRouteRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceClusterRouteRoute = WorkspaceClusterRouteRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAuditLogsRouteRoute = WorkspaceAuditLogsRouteRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAdaptiveRoutingRouteRoute =
  WorkspaceAdaptiveRoutingRouteRouteImport.update({
    id: '/adaptive-routing',
    path: '/adaptive-routing',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceVirtualKeysIndexRoute =
  WorkspaceVirtualKeysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceVirtualKeysRouteRoute,
  } as any)
const WorkspaceScimIndexRoute = WorkspaceScimIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceScimRouteRoute,
} as any)
const WorkspaceRoutingRulesIndexRoute =
  WorkspaceRoutingRulesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceRoutingRulesRouteRoute,
  } as any)
const WorkspaceRbacIndexRoute = WorkspaceRbacIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRbacRouteRoute,
} as any)
const WorkspaceProvidersIndexRoute = WorkspaceProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceProvidersRouteRoute,
} as any)
const WorkspacePluginsIndexRoute = WorkspacePluginsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacePluginsRouteRoute,
} as any)
const WorkspacePiiRedactorIndexRoute =
  WorkspacePiiRedactorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacePiiRedactorRouteRoute,
  } as any)
const WorkspaceObservabilityIndexRoute =
  WorkspaceObservabilityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceObservabilityRouteRoute,
  } as any)
const WorkspaceModelLimitsIndexRoute =
  WorkspaceModelLimitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceModelLimitsRouteRoute,
  } as any)
const WorkspaceModelCatalogIndexRoute =
  WorkspaceModelCatalogIndexRouteImport.update({
    id: '/model-catalog/',
    path: '/model-catalog/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceMcpToolGroupsIndexRoute =
  WorkspaceMcpToolGroupsIndexRouteImport.update({
    id: '/mcp-tool-groups/',
    path: '/mcp-tool-groups/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceMcpSettingsIndexRoute =
  WorkspaceMcpSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceMcpSettingsRouteRoute,
  } as any)
const WorkspaceMcpRegistryIndexRoute =
  WorkspaceMcpRegistryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceMcpRegistryRouteRoute,
  } as any)
const WorkspaceMcpLogsIndexRoute = WorkspaceMcpLogsIndexRouteImport.update({
  id: '/mcp-logs/',
  path: '/mcp-logs/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceMcpAuthConfigIndexRoute =
  WorkspaceMcpAuthConfigIndexRouteImport.update({
    id: '/mcp-auth-config/',
    path: '/mcp-auth-config/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceLogsIndexRoute = WorkspaceLogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceLogsRouteRoute,
} as any)
const WorkspaceGuardrailsIndexRoute =
  WorkspaceGuardrailsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceGuardrailsRouteRoute,
  } as any)
const WorkspaceGovernanceIndexRoute =
  WorkspaceGovernanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceGovernanceRouteRoute,
  } as any)
const WorkspaceDocsIndexRoute = WorkspaceDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceDashboardIndexRoute = WorkspaceDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceDashboardRouteRoute,
} as any)
const WorkspaceCustomPricingIndexRoute =
  WorkspaceCustomPricingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceCustomPricingRouteRoute,
  } as any)
const WorkspaceConfigIndexRoute = WorkspaceConfigIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceConfigRouteRoute,
} as any)
const WorkspaceClusterIndexRoute = WorkspaceClusterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceClusterRouteRoute,
} as any)
const WorkspaceAuditLogsIndexRoute = WorkspaceAuditLogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceAuditLogsRouteRoute,
} as any)
const WorkspaceAlertChannelsIndexRoute =
  WorkspaceAlertChannelsIndexRouteImport.update({
    id: '/alert-channels/',
    path: '/alert-channels/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceAdaptiveRoutingIndexRoute =
  WorkspaceAdaptiveRoutingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceAdaptiveRoutingRouteRoute,
  } as any)
const WorkspaceLogsDashboardRouteRoute =
  WorkspaceLogsDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => WorkspaceLogsRouteRoute,
  } as any)
const WorkspaceProvidersRoutingRulesIndexRoute =
  WorkspaceProvidersRoutingRulesIndexRouteImport.update({
    id: '/routing-rules/',
    path: '/routing-rules/',
    getParentRoute: () => WorkspaceProvidersRouteRoute,
  } as any)
const WorkspaceProvidersModelLimitsIndexRoute =
  WorkspaceProvidersModelLimitsIndexRouteImport.update({
    id: '/model-limits/',
    path: '/model-limits/',
    getParentRoute: () => WorkspaceProvidersRouteRoute,
  } as any)
const WorkspacePromptRepoPromptsIndexRoute =
  WorkspacePromptRepoPromptsIndexRouteImport.update({
    id: '/prompt-repo/prompts/',
    path: '/prompt-repo/prompts/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspacePromptRepoDeploymentsIndexRoute =
  WorkspacePromptRepoDeploymentsIndexRouteImport.update({
    id: '/prompt-repo/deployments/',
    path: '/prompt-repo/deployments/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspacePiiRedactorRulesIndexRoute =
  WorkspacePiiRedactorRulesIndexRouteImport.update({
    id: '/rules/',
    path: '/rules/',
    getParentRoute: () => WorkspacePiiRedactorRouteRoute,
  } as any)
const WorkspacePiiRedactorProvidersIndexRoute =
  WorkspacePiiRedactorProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => WorkspacePiiRedactorRouteRoute,
  } as any)
const WorkspaceLogsMcpLogsIndexRoute =
  WorkspaceLogsMcpLogsIndexRouteImport.update({
    id: '/mcp-logs/',
    path: '/mcp-logs/',
    getParentRoute: () => WorkspaceLogsRouteRoute,
  } as any)
const WorkspaceLogsDashboardIndexRoute =
  WorkspaceLogsDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceLogsDashboardRouteRoute,
  } as any)
const WorkspaceLogsConnectorsIndexRoute =
  WorkspaceLogsConnectorsIndexRouteImport.update({
    id: '/connectors/',
    path: '/connectors/',
    getParentRoute: () => WorkspaceLogsRouteRoute,
  } as any)
const WorkspaceGuardrailsProvidersIndexRoute =
  WorkspaceGuardrailsProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => WorkspaceGuardrailsRouteRoute,
  } as any)
const WorkspaceGuardrailsConfigurationIndexRoute =
  WorkspaceGuardrailsConfigurationIndexRouteImport.update({
    id: '/configuration/',
    path: '/configuration/',
    getParentRoute: () => WorkspaceGuardrailsRouteRoute,
  } as any)
const WorkspaceGovernanceVirtualKeysIndexRoute =
  WorkspaceGovernanceVirtualKeysIndexRouteImport.update({
    id: '/virtual-keys/',
    path: '/virtual-keys/',
    getParentRoute: () => WorkspaceGovernanceRouteRoute,
  } as any)
const WorkspaceGovernanceUsersIndexRoute =
  WorkspaceGovernanceUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => WorkspaceGovernanceRouteRoute,
  } as any)
const WorkspaceGovernanceTeamsIndexRoute =
  WorkspaceGovernanceTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => WorkspaceGovernanceRouteRoute,
  } as any)
const WorkspaceGovernanceRbacIndexRoute =
  WorkspaceGovernanceRbacIndexRouteImport.update({
    id: '/rbac/',
    path: '/rbac/',
    getParentRoute: () => WorkspaceGovernanceRouteRoute,
  } as any)
const WorkspaceGovernanceCustomersIndexRoute =
  WorkspaceGovernanceCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => WorkspaceGovernanceRouteRoute,
  } as any)
const WorkspaceConfigSecurityIndexRoute =
  WorkspaceConfigSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)
const WorkspaceConfigProxyIndexRoute =
  WorkspaceConfigProxyIndexRouteImport.update({
    id: '/proxy/',
    path: '/proxy/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)
const WorkspaceConfigPricingConfigIndexRoute =
  WorkspaceConfigPricingConfigIndexRouteImport.update({
    id: '/pricing-config/',
    path: '/pricing-config/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)
const WorkspaceConfigPerformanceTuningIndexRoute =
  WorkspaceConfigPerformanceTuningIndexRouteImport.update({
    id: '/performance-tuning/',
    path: '/performance-tuning/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)
const WorkspaceConfigObservabilityIndexRoute =
  WorkspaceConfigObservabilityIndexRouteImport.update({
    id: '/observability/',
    path: '/observability/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)
const WorkspaceConfigMcpGatewayIndexRoute =
  WorkspaceConfigMcpGatewayIndexRouteImport.update({
    id: '/mcp-gateway/',
    path: '/mcp-gateway/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)
const WorkspaceConfigLoggingIndexRoute =
  WorkspaceConfigLoggingIndexRouteImport.update({
    id: '/logging/',
    path: '/logging/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)
const WorkspaceConfigLargePayloadIndexRoute =
  WorkspaceConfigLargePayloadIndexRouteImport.update({
    id: '/large-payload/',
    path: '/large-payload/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)
const WorkspaceConfigClientSettingsIndexRoute =
  WorkspaceConfigClientSettingsIndexRouteImport.update({
    id: '/client-settings/',
    path: '/client-settings/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)
const WorkspaceConfigCachingIndexRoute =
  WorkspaceConfigCachingIndexRouteImport.update({
    id: '/caching/',
    path: '/caching/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)
const WorkspaceConfigApiKeysIndexRoute =
  WorkspaceConfigApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => WorkspaceConfigRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/pprof': typeof PprofRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/workspace/adaptive-routing': typeof WorkspaceAdaptiveRoutingRouteRouteWithChildren
  '/workspace/audit-logs': typeof WorkspaceAuditLogsRouteRouteWithChildren
  '/workspace/cluster': typeof WorkspaceClusterRouteRouteWithChildren
  '/workspace/config': typeof WorkspaceConfigRouteRouteWithChildren
  '/workspace/custom-pricing': typeof WorkspaceCustomPricingRouteRouteWithChildren
  '/workspace/dashboard': typeof WorkspaceDashboardRouteRouteWithChildren
  '/workspace/governance': typeof WorkspaceGovernanceRouteRouteWithChildren
  '/workspace/guardrails': typeof WorkspaceGuardrailsRouteRouteWithChildren
  '/workspace/logs': typeof WorkspaceLogsRouteRouteWithChildren
  '/workspace/mcp-registry': typeof WorkspaceMcpRegistryRouteRouteWithChildren
  '/workspace/mcp-settings': typeof WorkspaceMcpSettingsRouteRouteWithChildren
  '/workspace/model-limits': typeof WorkspaceModelLimitsRouteRouteWithChildren
  '/workspace/observability': typeof WorkspaceObservabilityRouteRouteWithChildren
  '/workspace/pii-redactor': typeof WorkspacePiiRedactorRouteRouteWithChildren
  '/workspace/plugins': typeof WorkspacePluginsRouteRouteWithChildren
  '/workspace/providers': typeof WorkspaceProvidersRouteRouteWithChildren
  '/workspace/rbac': typeof WorkspaceRbacRouteRouteWithChildren
  '/workspace/routing-rules': typeof WorkspaceRoutingRulesRouteRouteWithChildren
  '/workspace/scim': typeof WorkspaceScimRouteRouteWithChildren
  '/workspace/virtual-keys': typeof WorkspaceVirtualKeysRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/pprof/': typeof PprofIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/logs/dashboard': typeof WorkspaceLogsDashboardRouteRouteWithChildren
  '/workspace/adaptive-routing/': typeof WorkspaceAdaptiveRoutingIndexRoute
  '/workspace/alert-channels/': typeof WorkspaceAlertChannelsIndexRoute
  '/workspace/audit-logs/': typeof WorkspaceAuditLogsIndexRoute
  '/workspace/cluster/': typeof WorkspaceClusterIndexRoute
  '/workspace/config/': typeof WorkspaceConfigIndexRoute
  '/workspace/custom-pricing/': typeof WorkspaceCustomPricingIndexRoute
  '/workspace/dashboard/': typeof WorkspaceDashboardIndexRoute
  '/workspace/docs/': typeof WorkspaceDocsIndexRoute
  '/workspace/governance/': typeof WorkspaceGovernanceIndexRoute
  '/workspace/guardrails/': typeof WorkspaceGuardrailsIndexRoute
  '/workspace/logs/': typeof WorkspaceLogsIndexRoute
  '/workspace/mcp-auth-config/': typeof WorkspaceMcpAuthConfigIndexRoute
  '/workspace/mcp-logs/': typeof WorkspaceMcpLogsIndexRoute
  '/workspace/mcp-registry/': typeof WorkspaceMcpRegistryIndexRoute
  '/workspace/mcp-settings/': typeof WorkspaceMcpSettingsIndexRoute
  '/workspace/mcp-tool-groups/': typeof WorkspaceMcpToolGroupsIndexRoute
  '/workspace/model-catalog/': typeof WorkspaceModelCatalogIndexRoute
  '/workspace/model-limits/': typeof WorkspaceModelLimitsIndexRoute
  '/workspace/observability/': typeof WorkspaceObservabilityIndexRoute
  '/workspace/pii-redactor/': typeof WorkspacePiiRedactorIndexRoute
  '/workspace/plugins/': typeof WorkspacePluginsIndexRoute
  '/workspace/providers/': typeof WorkspaceProvidersIndexRoute
  '/workspace/rbac/': typeof WorkspaceRbacIndexRoute
  '/workspace/routing-rules/': typeof WorkspaceRoutingRulesIndexRoute
  '/workspace/scim/': typeof WorkspaceScimIndexRoute
  '/workspace/virtual-keys/': typeof WorkspaceVirtualKeysIndexRoute
  '/workspace/config/api-keys/': typeof WorkspaceConfigApiKeysIndexRoute
  '/workspace/config/caching/': typeof WorkspaceConfigCachingIndexRoute
  '/workspace/config/client-settings/': typeof WorkspaceConfigClientSettingsIndexRoute
  '/workspace/config/large-payload/': typeof WorkspaceConfigLargePayloadIndexRoute
  '/workspace/config/logging/': typeof WorkspaceConfigLoggingIndexRoute
  '/workspace/config/mcp-gateway/': typeof WorkspaceConfigMcpGatewayIndexRoute
  '/workspace/config/observability/': typeof WorkspaceConfigObservabilityIndexRoute
  '/workspace/config/performance-tuning/': typeof WorkspaceConfigPerformanceTuningIndexRoute
  '/workspace/config/pricing-config/': typeof WorkspaceConfigPricingConfigIndexRoute
  '/workspace/config/proxy/': typeof WorkspaceConfigProxyIndexRoute
  '/workspace/config/security/': typeof WorkspaceConfigSecurityIndexRoute
  '/workspace/governance/customers/': typeof WorkspaceGovernanceCustomersIndexRoute
  '/workspace/governance/rbac/': typeof WorkspaceGovernanceRbacIndexRoute
  '/workspace/governance/teams/': typeof WorkspaceGovernanceTeamsIndexRoute
  '/workspace/governance/users/': typeof WorkspaceGovernanceUsersIndexRoute
  '/workspace/governance/virtual-keys/': typeof WorkspaceGovernanceVirtualKeysIndexRoute
  '/workspace/guardrails/configuration/': typeof WorkspaceGuardrailsConfigurationIndexRoute
  '/workspace/guardrails/providers/': typeof WorkspaceGuardrailsProvidersIndexRoute
  '/workspace/logs/connectors/': typeof WorkspaceLogsConnectorsIndexRoute
  '/workspace/logs/dashboard/': typeof WorkspaceLogsDashboardIndexRoute
  '/workspace/logs/mcp-logs/': typeof WorkspaceLogsMcpLogsIndexRoute
  '/workspace/pii-redactor/providers/': typeof WorkspacePiiRedactorProvidersIndexRoute
  '/workspace/pii-redactor/rules/': typeof WorkspacePiiRedactorRulesIndexRoute
  '/workspace/prompt-repo/deployments/': typeof WorkspacePromptRepoDeploymentsIndexRoute
  '/workspace/prompt-repo/prompts/': typeof WorkspacePromptRepoPromptsIndexRoute
  '/workspace/providers/model-limits/': typeof WorkspaceProvidersModelLimitsIndexRoute
  '/workspace/providers/routing-rules/': typeof WorkspaceProvidersRoutingRulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/pprof': typeof PprofIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/adaptive-routing': typeof WorkspaceAdaptiveRoutingIndexRoute
  '/workspace/alert-channels': typeof WorkspaceAlertChannelsIndexRoute
  '/workspace/audit-logs': typeof WorkspaceAuditLogsIndexRoute
  '/workspace/cluster': typeof WorkspaceClusterIndexRoute
  '/workspace/config': typeof WorkspaceConfigIndexRoute
  '/workspace/custom-pricing': typeof WorkspaceCustomPricingIndexRoute
  '/workspace/dashboard': typeof WorkspaceDashboardIndexRoute
  '/workspace/docs': typeof WorkspaceDocsIndexRoute
  '/workspace/governance': typeof WorkspaceGovernanceIndexRoute
  '/workspace/guardrails': typeof WorkspaceGuardrailsIndexRoute
  '/workspace/logs': typeof WorkspaceLogsIndexRoute
  '/workspace/mcp-auth-config': typeof WorkspaceMcpAuthConfigIndexRoute
  '/workspace/mcp-logs': typeof WorkspaceMcpLogsIndexRoute
  '/workspace/mcp-registry': typeof WorkspaceMcpRegistryIndexRoute
  '/workspace/mcp-settings': typeof WorkspaceMcpSettingsIndexRoute
  '/workspace/mcp-tool-groups': typeof WorkspaceMcpToolGroupsIndexRoute
  '/workspace/model-catalog': typeof WorkspaceModelCatalogIndexRoute
  '/workspace/model-limits': typeof WorkspaceModelLimitsIndexRoute
  '/workspace/observability': typeof WorkspaceObservabilityIndexRoute
  '/workspace/pii-redactor': typeof WorkspacePiiRedactorIndexRoute
  '/workspace/plugins': typeof WorkspacePluginsIndexRoute
  '/workspace/providers': typeof WorkspaceProvidersIndexRoute
  '/workspace/rbac': typeof WorkspaceRbacIndexRoute
  '/workspace/routing-rules': typeof WorkspaceRoutingRulesIndexRoute
  '/workspace/scim': typeof WorkspaceScimIndexRoute
  '/workspace/virtual-keys': typeof WorkspaceVirtualKeysIndexRoute
  '/workspace/config/api-keys': typeof WorkspaceConfigApiKeysIndexRoute
  '/workspace/config/caching': typeof WorkspaceConfigCachingIndexRoute
  '/workspace/config/client-settings': typeof WorkspaceConfigClientSettingsIndexRoute
  '/workspace/config/large-payload': typeof WorkspaceConfigLargePayloadIndexRoute
  '/workspace/config/logging': typeof WorkspaceConfigLoggingIndexRoute
  '/workspace/config/mcp-gateway': typeof WorkspaceConfigMcpGatewayIndexRoute
  '/workspace/config/observability': typeof WorkspaceConfigObservabilityIndexRoute
  '/workspace/config/performance-tuning': typeof WorkspaceConfigPerformanceTuningIndexRoute
  '/workspace/config/pricing-config': typeof WorkspaceConfigPricingConfigIndexRoute
  '/workspace/config/proxy': typeof WorkspaceConfigProxyIndexRoute
  '/workspace/config/security': typeof WorkspaceConfigSecurityIndexRoute
  '/workspace/governance/customers': typeof WorkspaceGovernanceCustomersIndexRoute
  '/workspace/governance/rbac': typeof WorkspaceGovernanceRbacIndexRoute
  '/workspace/governance/teams': typeof WorkspaceGovernanceTeamsIndexRoute
  '/workspace/governance/users': typeof WorkspaceGovernanceUsersIndexRoute
  '/workspace/governance/virtual-keys': typeof WorkspaceGovernanceVirtualKeysIndexRoute
  '/workspace/guardrails/configuration': typeof WorkspaceGuardrailsConfigurationIndexRoute
  '/workspace/guardrails/providers': typeof WorkspaceGuardrailsProvidersIndexRoute
  '/workspace/logs/connectors': typeof WorkspaceLogsConnectorsIndexRoute
  '/workspace/logs/dashboard': typeof WorkspaceLogsDashboardIndexRoute
  '/workspace/logs/mcp-logs': typeof WorkspaceLogsMcpLogsIndexRoute
  '/workspace/pii-redactor/providers': typeof WorkspacePiiRedactorProvidersIndexRoute
  '/workspace/pii-redactor/rules': typeof WorkspacePiiRedactorRulesIndexRoute
  '/workspace/prompt-repo/deployments': typeof WorkspacePromptRepoDeploymentsIndexRoute
  '/workspace/prompt-repo/prompts': typeof WorkspacePromptRepoPromptsIndexRoute
  '/workspace/providers/model-limits': typeof WorkspaceProvidersModelLimitsIndexRoute
  '/workspace/providers/routing-rules': typeof WorkspaceProvidersRoutingRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/pprof': typeof PprofRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/workspace/adaptive-routing': typeof WorkspaceAdaptiveRoutingRouteRouteWithChildren
  '/workspace/audit-logs': typeof WorkspaceAuditLogsRouteRouteWithChildren
  '/workspace/cluster': typeof WorkspaceClusterRouteRouteWithChildren
  '/workspace/config': typeof WorkspaceConfigRouteRouteWithChildren
  '/workspace/custom-pricing': typeof WorkspaceCustomPricingRouteRouteWithChildren
  '/workspace/dashboard': typeof WorkspaceDashboardRouteRouteWithChildren
  '/workspace/governance': typeof WorkspaceGovernanceRouteRouteWithChildren
  '/workspace/guardrails': typeof WorkspaceGuardrailsRouteRouteWithChildren
  '/workspace/logs': typeof WorkspaceLogsRouteRouteWithChildren
  '/workspace/mcp-registry': typeof WorkspaceMcpRegistryRouteRouteWithChildren
  '/workspace/mcp-settings': typeof WorkspaceMcpSettingsRouteRouteWithChildren
  '/workspace/model-limits': typeof WorkspaceModelLimitsRouteRouteWithChildren
  '/workspace/observability': typeof WorkspaceObservabilityRouteRouteWithChildren
  '/workspace/pii-redactor': typeof WorkspacePiiRedactorRouteRouteWithChildren
  '/workspace/plugins': typeof WorkspacePluginsRouteRouteWithChildren
  '/workspace/providers': typeof WorkspaceProvidersRouteRouteWithChildren
  '/workspace/rbac': typeof WorkspaceRbacRouteRouteWithChildren
  '/workspace/routing-rules': typeof WorkspaceRoutingRulesRouteRouteWithChildren
  '/workspace/scim': typeof WorkspaceScimRouteRouteWithChildren
  '/workspace/virtual-keys': typeof WorkspaceVirtualKeysRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/pprof/': typeof PprofIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/logs/dashboard': typeof WorkspaceLogsDashboardRouteRouteWithChildren
  '/workspace/adaptive-routing/': typeof WorkspaceAdaptiveRoutingIndexRoute
  '/workspace/alert-channels/': typeof WorkspaceAlertChannelsIndexRoute
  '/workspace/audit-logs/': typeof WorkspaceAuditLogsIndexRoute
  '/workspace/cluster/': typeof WorkspaceClusterIndexRoute
  '/workspace/config/': typeof WorkspaceConfigIndexRoute
  '/workspace/custom-pricing/': typeof WorkspaceCustomPricingIndexRoute
  '/workspace/dashboard/': typeof WorkspaceDashboardIndexRoute
  '/workspace/docs/': typeof WorkspaceDocsIndexRoute
  '/workspace/governance/': typeof WorkspaceGovernanceIndexRoute
  '/workspace/guardrails/': typeof WorkspaceGuardrailsIndexRoute
  '/workspace/logs/': typeof WorkspaceLogsIndexRoute
  '/workspace/mcp-auth-config/': typeof WorkspaceMcpAuthConfigIndexRoute
  '/workspace/mcp-logs/': typeof WorkspaceMcpLogsIndexRoute
  '/workspace/mcp-registry/': typeof WorkspaceMcpRegistryIndexRoute
  '/workspace/mcp-settings/': typeof WorkspaceMcpSettingsIndexRoute
  '/workspace/mcp-tool-groups/': typeof WorkspaceMcpToolGroupsIndexRoute
  '/workspace/model-catalog/': typeof WorkspaceModelCatalogIndexRoute
  '/workspace/model-limits/': typeof WorkspaceModelLimitsIndexRoute
  '/workspace/observability/': typeof WorkspaceObservabilityIndexRoute
  '/workspace/pii-redactor/': typeof WorkspacePiiRedactorIndexRoute
  '/workspace/plugins/': typeof WorkspacePluginsIndexRoute
  '/workspace/providers/': typeof WorkspaceProvidersIndexRoute
  '/workspace/rbac/': typeof WorkspaceRbacIndexRoute
  '/workspace/routing-rules/': typeof WorkspaceRoutingRulesIndexRoute
  '/workspace/scim/': typeof WorkspaceScimIndexRoute
  '/workspace/virtual-keys/': typeof WorkspaceVirtualKeysIndexRoute
  '/workspace/config/api-keys/': typeof WorkspaceConfigApiKeysIndexRoute
  '/workspace/config/caching/': typeof WorkspaceConfigCachingIndexRoute
  '/workspace/config/client-settings/': typeof WorkspaceConfigClientSettingsIndexRoute
  '/workspace/config/large-payload/': typeof WorkspaceConfigLargePayloadIndexRoute
  '/workspace/config/logging/': typeof WorkspaceConfigLoggingIndexRoute
  '/workspace/config/mcp-gateway/': typeof WorkspaceConfigMcpGatewayIndexRoute
  '/workspace/config/observability/': typeof WorkspaceConfigObservabilityIndexRoute
  '/workspace/config/performance-tuning/': typeof WorkspaceConfigPerformanceTuningIndexRoute
  '/workspace/config/pricing-config/': typeof WorkspaceConfigPricingConfigIndexRoute
  '/workspace/config/proxy/': typeof WorkspaceConfigProxyIndexRoute
  '/workspace/config/security/': typeof WorkspaceConfigSecurityIndexRoute
  '/workspace/governance/customers/': typeof WorkspaceGovernanceCustomersIndexRoute
  '/workspace/governance/rbac/': typeof WorkspaceGovernanceRbacIndexRoute
  '/workspace/governance/teams/': typeof WorkspaceGovernanceTeamsIndexRoute
  '/workspace/governance/users/': typeof WorkspaceGovernanceUsersIndexRoute
  '/workspace/governance/virtual-keys/': typeof WorkspaceGovernanceVirtualKeysIndexRoute
  '/workspace/guardrails/configuration/': typeof WorkspaceGuardrailsConfigurationIndexRoute
  '/workspace/guardrails/providers/': typeof WorkspaceGuardrailsProvidersIndexRoute
  '/workspace/logs/connectors/': typeof WorkspaceLogsConnectorsIndexRoute
  '/workspace/logs/dashboard/': typeof WorkspaceLogsDashboardIndexRoute
  '/workspace/logs/mcp-logs/': typeof WorkspaceLogsMcpLogsIndexRoute
  '/workspace/pii-redactor/providers/': typeof WorkspacePiiRedactorProvidersIndexRoute
  '/workspace/pii-redactor/rules/': typeof WorkspacePiiRedactorRulesIndexRoute
  '/workspace/prompt-repo/deployments/': typeof WorkspacePromptRepoDeploymentsIndexRoute
  '/workspace/prompt-repo/prompts/': typeof WorkspacePromptRepoPromptsIndexRoute
  '/workspace/providers/model-limits/': typeof WorkspaceProvidersModelLimitsIndexRoute
  '/workspace/providers/routing-rules/': typeof WorkspaceProvidersRoutingRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pprof'
    | '/workspace'
    | '/workspace/adaptive-routing'
    | '/workspace/audit-logs'
    | '/workspace/cluster'
    | '/workspace/config'
    | '/workspace/custom-pricing'
    | '/workspace/dashboard'
    | '/workspace/governance'
    | '/workspace/guardrails'
    | '/workspace/logs'
    | '/workspace/mcp-registry'
    | '/workspace/mcp-settings'
    | '/workspace/model-limits'
    | '/workspace/observability'
    | '/workspace/pii-redactor'
    | '/workspace/plugins'
    | '/workspace/providers'
    | '/workspace/rbac'
    | '/workspace/routing-rules'
    | '/workspace/scim'
    | '/workspace/virtual-keys'
    | '/login/'
    | '/pprof/'
    | '/workspace/'
    | '/workspace/logs/dashboard'
    | '/workspace/adaptive-routing/'
    | '/workspace/alert-channels/'
    | '/workspace/audit-logs/'
    | '/workspace/cluster/'
    | '/workspace/config/'
    | '/workspace/custom-pricing/'
    | '/workspace/dashboard/'
    | '/workspace/docs/'
    | '/workspace/governance/'
    | '/workspace/guardrails/'
    | '/workspace/logs/'
    | '/workspace/mcp-auth-config/'
    | '/workspace/mcp-logs/'
    | '/workspace/mcp-registry/'
    | '/workspace/mcp-settings/'
    | '/workspace/mcp-tool-groups/'
    | '/workspace/model-catalog/'
    | '/workspace/model-limits/'
    | '/workspace/observability/'
    | '/workspace/pii-redactor/'
    | '/workspace/plugins/'
    | '/workspace/providers/'
    | '/workspace/rbac/'
    | '/workspace/routing-rules/'
    | '/workspace/scim/'
    | '/workspace/virtual-keys/'
    | '/workspace/config/api-keys/'
    | '/workspace/config/caching/'
    | '/workspace/config/client-settings/'
    | '/workspace/config/large-payload/'
    | '/workspace/config/logging/'
    | '/workspace/config/mcp-gateway/'
    | '/workspace/config/observability/'
    | '/workspace/config/performance-tuning/'
    | '/workspace/config/pricing-config/'
    | '/workspace/config/proxy/'
    | '/workspace/config/security/'
    | '/workspace/governance/customers/'
    | '/workspace/governance/rbac/'
    | '/workspace/governance/teams/'
    | '/workspace/governance/users/'
    | '/workspace/governance/virtual-keys/'
    | '/workspace/guardrails/configuration/'
    | '/workspace/guardrails/providers/'
    | '/workspace/logs/connectors/'
    | '/workspace/logs/dashboard/'
    | '/workspace/logs/mcp-logs/'
    | '/workspace/pii-redactor/providers/'
    | '/workspace/pii-redactor/rules/'
    | '/workspace/prompt-repo/deployments/'
    | '/workspace/prompt-repo/prompts/'
    | '/workspace/providers/model-limits/'
    | '/workspace/providers/routing-rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pprof'
    | '/workspace'
    | '/workspace/adaptive-routing'
    | '/workspace/alert-channels'
    | '/workspace/audit-logs'
    | '/workspace/cluster'
    | '/workspace/config'
    | '/workspace/custom-pricing'
    | '/workspace/dashboard'
    | '/workspace/docs'
    | '/workspace/governance'
    | '/workspace/guardrails'
    | '/workspace/logs'
    | '/workspace/mcp-auth-config'
    | '/workspace/mcp-logs'
    | '/workspace/mcp-registry'
    | '/workspace/mcp-settings'
    | '/workspace/mcp-tool-groups'
    | '/workspace/model-catalog'
    | '/workspace/model-limits'
    | '/workspace/observability'
    | '/workspace/pii-redactor'
    | '/workspace/plugins'
    | '/workspace/providers'
    | '/workspace/rbac'
    | '/workspace/routing-rules'
    | '/workspace/scim'
    | '/workspace/virtual-keys'
    | '/workspace/config/api-keys'
    | '/workspace/config/caching'
    | '/workspace/config/client-settings'
    | '/workspace/config/large-payload'
    | '/workspace/config/logging'
    | '/workspace/config/mcp-gateway'
    | '/workspace/config/observability'
    | '/workspace/config/performance-tuning'
    | '/workspace/config/pricing-config'
    | '/workspace/config/proxy'
    | '/workspace/config/security'
    | '/workspace/governance/customers'
    | '/workspace/governance/rbac'
    | '/workspace/governance/teams'
    | '/workspace/governance/users'
    | '/workspace/governance/virtual-keys'
    | '/workspace/guardrails/configuration'
    | '/workspace/guardrails/providers'
    | '/workspace/logs/connectors'
    | '/workspace/logs/dashboard'
    | '/workspace/logs/mcp-logs'
    | '/workspace/pii-redactor/providers'
    | '/workspace/pii-redactor/rules'
    | '/workspace/prompt-repo/deployments'
    | '/workspace/prompt-repo/prompts'
    | '/workspace/providers/model-limits'
    | '/workspace/providers/routing-rules'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pprof'
    | '/workspace'
    | '/workspace/adaptive-routing'
    | '/workspace/audit-logs'
    | '/workspace/cluster'
    | '/workspace/config'
    | '/workspace/custom-pricing'
    | '/workspace/dashboard'
    | '/workspace/governance'
    | '/workspace/guardrails'
    | '/workspace/logs'
    | '/workspace/mcp-registry'
    | '/workspace/mcp-settings'
    | '/workspace/model-limits'
    | '/workspace/observability'
    | '/workspace/pii-redactor'
    | '/workspace/plugins'
    | '/workspace/providers'
    | '/workspace/rbac'
    | '/workspace/routing-rules'
    | '/workspace/scim'
    | '/workspace/virtual-keys'
    | '/login/'
    | '/pprof/'
    | '/workspace/'
    | '/workspace/logs/dashboard'
    | '/workspace/adaptive-routing/'
    | '/workspace/alert-channels/'
    | '/workspace/audit-logs/'
    | '/workspace/cluster/'
    | '/workspace/config/'
    | '/workspace/custom-pricing/'
    | '/workspace/dashboard/'
    | '/workspace/docs/'
    | '/workspace/governance/'
    | '/workspace/guardrails/'
    | '/workspace/logs/'
    | '/workspace/mcp-auth-config/'
    | '/workspace/mcp-logs/'
    | '/workspace/mcp-registry/'
    | '/workspace/mcp-settings/'
    | '/workspace/mcp-tool-groups/'
    | '/workspace/model-catalog/'
    | '/workspace/model-limits/'
    | '/workspace/observability/'
    | '/workspace/pii-redactor/'
    | '/workspace/plugins/'
    | '/workspace/providers/'
    | '/workspace/rbac/'
    | '/workspace/routing-rules/'
    | '/workspace/scim/'
    | '/workspace/virtual-keys/'
    | '/workspace/config/api-keys/'
    | '/workspace/config/caching/'
    | '/workspace/config/client-settings/'
    | '/workspace/config/large-payload/'
    | '/workspace/config/logging/'
    | '/workspace/config/mcp-gateway/'
    | '/workspace/config/observability/'
    | '/workspace/config/performance-tuning/'
    | '/workspace/config/pricing-config/'
    | '/workspace/config/proxy/'
    | '/workspace/config/security/'
    | '/workspace/governance/customers/'
    | '/workspace/governance/rbac/'
    | '/workspace/governance/teams/'
    | '/workspace/governance/users/'
    | '/workspace/governance/virtual-keys/'
    | '/workspace/guardrails/configuration/'
    | '/workspace/guardrails/providers/'
    | '/workspace/logs/connectors/'
    | '/workspace/logs/dashboard/'
    | '/workspace/logs/mcp-logs/'
    | '/workspace/pii-redactor/providers/'
    | '/workspace/pii-redactor/rules/'
    | '/workspace/prompt-repo/deployments/'
    | '/workspace/prompt-repo/prompts/'
    | '/workspace/providers/model-limits/'
    | '/workspace/providers/routing-rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  PprofRouteRoute: typeof PprofRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pprof': {
      id: '/pprof'
      path: '/pprof'
      fullPath: '/pprof'
      preLoaderRoute: typeof PprofRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/pprof/': {
      id: '/pprof/'
      path: '/'
      fullPath: '/pprof/'
      preLoaderRoute: typeof PprofIndexRouteImport
      parentRoute: typeof PprofRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/workspace/virtual-keys': {
      id: '/workspace/virtual-keys'
      path: '/virtual-keys'
      fullPath: '/workspace/virtual-keys'
      preLoaderRoute: typeof WorkspaceVirtualKeysRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/scim': {
      id: '/workspace/scim'
      path: '/scim'
      fullPath: '/workspace/scim'
      preLoaderRoute: typeof WorkspaceScimRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/routing-rules': {
      id: '/workspace/routing-rules'
      path: '/routing-rules'
      fullPath: '/workspace/routing-rules'
      preLoaderRoute: typeof WorkspaceRoutingRulesRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/rbac': {
      id: '/workspace/rbac'
      path: '/rbac'
      fullPath: '/workspace/rbac'
      preLoaderRoute: typeof WorkspaceRbacRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/providers': {
      id: '/workspace/providers'
      path: '/providers'
      fullPath: '/workspace/providers'
      preLoaderRoute: typeof WorkspaceProvidersRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/plugins': {
      id: '/workspace/plugins'
      path: '/plugins'
      fullPath: '/workspace/plugins'
      preLoaderRoute: typeof WorkspacePluginsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/pii-redactor': {
      id: '/workspace/pii-redactor'
      path: '/pii-redactor'
      fullPath: '/workspace/pii-redactor'
      preLoaderRoute: typeof WorkspacePiiRedactorRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/observability': {
      id: '/workspace/observability'
      path: '/observability'
      fullPath: '/workspace/observability'
      preLoaderRoute: typeof WorkspaceObservabilityRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/model-limits': {
      id: '/workspace/model-limits'
      path: '/model-limits'
      fullPath: '/workspace/model-limits'
      preLoaderRoute: typeof WorkspaceModelLimitsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/mcp-settings': {
      id: '/workspace/mcp-settings'
      path: '/mcp-settings'
      fullPath: '/workspace/mcp-settings'
      preLoaderRoute: typeof WorkspaceMcpSettingsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/mcp-registry': {
      id: '/workspace/mcp-registry'
      path: '/mcp-registry'
      fullPath: '/workspace/mcp-registry'
      preLoaderRoute: typeof WorkspaceMcpRegistryRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/logs': {
      id: '/workspace/logs'
      path: '/logs'
      fullPath: '/workspace/logs'
      preLoaderRoute: typeof WorkspaceLogsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/guardrails': {
      id: '/workspace/guardrails'
      path: '/guardrails'
      fullPath: '/workspace/guardrails'
      preLoaderRoute: typeof WorkspaceGuardrailsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/governance': {
      id: '/workspace/governance'
      path: '/governance'
      fullPath: '/workspace/governance'
      preLoaderRoute: typeof WorkspaceGovernanceRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/dashboard': {
      id: '/workspace/dashboard'
      path: '/dashboard'
      fullPath: '/workspace/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/custom-pricing': {
      id: '/workspace/custom-pricing'
      path: '/custom-pricing'
      fullPath: '/workspace/custom-pricing'
      preLoaderRoute: typeof WorkspaceCustomPricingRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/config': {
      id: '/workspace/config'
      path: '/config'
      fullPath: '/workspace/config'
      preLoaderRoute: typeof WorkspaceConfigRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/cluster': {
      id: '/workspace/cluster'
      path: '/cluster'
      fullPath: '/workspace/cluster'
      preLoaderRoute: typeof WorkspaceClusterRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/audit-logs': {
      id: '/workspace/audit-logs'
      path: '/audit-logs'
      fullPath: '/workspace/audit-logs'
      preLoaderRoute: typeof WorkspaceAuditLogsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/adaptive-routing': {
      id: '/workspace/adaptive-routing'
      path: '/adaptive-routing'
      fullPath: '/workspace/adaptive-routing'
      preLoaderRoute: typeof WorkspaceAdaptiveRoutingRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/virtual-keys/': {
      id: '/workspace/virtual-keys/'
      path: '/'
      fullPath: '/workspace/virtual-keys/'
      preLoaderRoute: typeof WorkspaceVirtualKeysIndexRouteImport
      parentRoute: typeof WorkspaceVirtualKeysRouteRoute
    }
    '/workspace/scim/': {
      id: '/workspace/scim/'
      path: '/'
      fullPath: '/workspace/scim/'
      preLoaderRoute: typeof WorkspaceScimIndexRouteImport
      parentRoute: typeof WorkspaceScimRouteRoute
    }
    '/workspace/routing-rules/': {
      id: '/workspace/routing-rules/'
      path: '/'
      fullPath: '/workspace/routing-rules/'
      preLoaderRoute: typeof WorkspaceRoutingRulesIndexRouteImport
      parentRoute: typeof WorkspaceRoutingRulesRouteRoute
    }
    '/workspace/rbac/': {
      id: '/workspace/rbac/'
      path: '/'
      fullPath: '/workspace/rbac/'
      preLoaderRoute: typeof WorkspaceRbacIndexRouteImport
      parentRoute: typeof WorkspaceRbacRouteRoute
    }
    '/workspace/providers/': {
      id: '/workspace/providers/'
      path: '/'
      fullPath: '/workspace/providers/'
      preLoaderRoute: typeof WorkspaceProvidersIndexRouteImport
      parentRoute: typeof WorkspaceProvidersRouteRoute
    }
    '/workspace/plugins/': {
      id: '/workspace/plugins/'
      path: '/'
      fullPath: '/workspace/plugins/'
      preLoaderRoute: typeof WorkspacePluginsIndexRouteImport
      parentRoute: typeof WorkspacePluginsRouteRoute
    }
    '/workspace/pii-redactor/': {
      id: '/workspace/pii-redactor/'
      path: '/'
      fullPath: '/workspace/pii-redactor/'
      preLoaderRoute: typeof WorkspacePiiRedactorIndexRouteImport
      parentRoute: typeof WorkspacePiiRedactorRouteRoute
    }
    '/workspace/observability/': {
      id: '/workspace/observability/'
      path: '/'
      fullPath: '/workspace/observability/'
      preLoaderRoute: typeof WorkspaceObservabilityIndexRouteImport
      parentRoute: typeof WorkspaceObservabilityRouteRoute
    }
    '/workspace/model-limits/': {
      id: '/workspace/model-limits/'
      path: '/'
      fullPath: '/workspace/model-limits/'
      preLoaderRoute: typeof WorkspaceModelLimitsIndexRouteImport
      parentRoute: typeof WorkspaceModelLimitsRouteRoute
    }
    '/workspace/model-catalog/': {
      id: '/workspace/model-catalog/'
      path: '/model-catalog'
      fullPath: '/workspace/model-catalog/'
      preLoaderRoute: typeof WorkspaceModelCatalogIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/mcp-tool-groups/': {
      id: '/workspace/mcp-tool-groups/'
      path: '/mcp-tool-groups'
      fullPath: '/workspace/mcp-tool-groups/'
      preLoaderRoute: typeof WorkspaceMcpToolGroupsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/mcp-settings/': {
      id: '/workspace/mcp-settings/'
      path: '/'
      fullPath: '/workspace/mcp-settings/'
      preLoaderRoute: typeof WorkspaceMcpSettingsIndexRouteImport
      parentRoute: typeof WorkspaceMcpSettingsRouteRoute
    }
    '/workspace/mcp-registry/': {
      id: '/workspace/mcp-registry/'
      path: '/'
      fullPath: '/workspace/mcp-registry/'
      preLoaderRoute: typeof WorkspaceMcpRegistryIndexRouteImport
      parentRoute: typeof WorkspaceMcpRegistryRouteRoute
    }
    '/workspace/mcp-logs/': {
      id: '/workspace/mcp-logs/'
      path: '/mcp-logs'
      fullPath: '/workspace/mcp-logs/'
      preLoaderRoute: typeof WorkspaceMcpLogsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/mcp-auth-config/': {
      id: '/workspace/mcp-auth-config/'
      path: '/mcp-auth-config'
      fullPath: '/workspace/mcp-auth-config/'
      preLoaderRoute: typeof WorkspaceMcpAuthConfigIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/logs/': {
      id: '/workspace/logs/'
      path: '/'
      fullPath: '/workspace/logs/'
      preLoaderRoute: typeof WorkspaceLogsIndexRouteImport
      parentRoute: typeof WorkspaceLogsRouteRoute
    }
    '/workspace/guardrails/': {
      id: '/workspace/guardrails/'
      path: '/'
      fullPath: '/workspace/guardrails/'
      preLoaderRoute: typeof WorkspaceGuardrailsIndexRouteImport
      parentRoute: typeof WorkspaceGuardrailsRouteRoute
    }
    '/workspace/governance/': {
      id: '/workspace/governance/'
      path: '/'
      fullPath: '/workspace/governance/'
      preLoaderRoute: typeof WorkspaceGovernanceIndexRouteImport
      parentRoute: typeof WorkspaceGovernanceRouteRoute
    }
    '/workspace/docs/': {
      id: '/workspace/docs/'
      path: '/docs'
      fullPath: '/workspace/docs/'
      preLoaderRoute: typeof WorkspaceDocsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/dashboard/': {
      id: '/workspace/dashboard/'
      path: '/'
      fullPath: '/workspace/dashboard/'
      preLoaderRoute: typeof WorkspaceDashboardIndexRouteImport
      parentRoute: typeof WorkspaceDashboardRouteRoute
    }
    '/workspace/custom-pricing/': {
      id: '/workspace/custom-pricing/'
      path: '/'
      fullPath: '/workspace/custom-pricing/'
      preLoaderRoute: typeof WorkspaceCustomPricingIndexRouteImport
      parentRoute: typeof WorkspaceCustomPricingRouteRoute
    }
    '/workspace/config/': {
      id: '/workspace/config/'
      path: '/'
      fullPath: '/workspace/config/'
      preLoaderRoute: typeof WorkspaceConfigIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/cluster/': {
      id: '/workspace/cluster/'
      path: '/'
      fullPath: '/workspace/cluster/'
      preLoaderRoute: typeof WorkspaceClusterIndexRouteImport
      parentRoute: typeof WorkspaceClusterRouteRoute
    }
    '/workspace/audit-logs/': {
      id: '/workspace/audit-logs/'
      path: '/'
      fullPath: '/workspace/audit-logs/'
      preLoaderRoute: typeof WorkspaceAuditLogsIndexRouteImport
      parentRoute: typeof WorkspaceAuditLogsRouteRoute
    }
    '/workspace/alert-channels/': {
      id: '/workspace/alert-channels/'
      path: '/alert-channels'
      fullPath: '/workspace/alert-channels/'
      preLoaderRoute: typeof WorkspaceAlertChannelsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/adaptive-routing/': {
      id: '/workspace/adaptive-routing/'
      path: '/'
      fullPath: '/workspace/adaptive-routing/'
      preLoaderRoute: typeof WorkspaceAdaptiveRoutingIndexRouteImport
      parentRoute: typeof WorkspaceAdaptiveRoutingRouteRoute
    }
    '/workspace/logs/dashboard': {
      id: '/workspace/logs/dashboard'
      path: '/dashboard'
      fullPath: '/workspace/logs/dashboard'
      preLoaderRoute: typeof WorkspaceLogsDashboardRouteRouteImport
      parentRoute: typeof WorkspaceLogsRouteRoute
    }
    '/workspace/providers/routing-rules/': {
      id: '/workspace/providers/routing-rules/'
      path: '/routing-rules'
      fullPath: '/workspace/providers/routing-rules/'
      preLoaderRoute: typeof WorkspaceProvidersRoutingRulesIndexRouteImport
      parentRoute: typeof WorkspaceProvidersRouteRoute
    }
    '/workspace/providers/model-limits/': {
      id: '/workspace/providers/model-limits/'
      path: '/model-limits'
      fullPath: '/workspace/providers/model-limits/'
      preLoaderRoute: typeof WorkspaceProvidersModelLimitsIndexRouteImport
      parentRoute: typeof WorkspaceProvidersRouteRoute
    }
    '/workspace/prompt-repo/prompts/': {
      id: '/workspace/prompt-repo/prompts/'
      path: '/prompt-repo/prompts'
      fullPath: '/workspace/prompt-repo/prompts/'
      preLoaderRoute: typeof WorkspacePromptRepoPromptsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/prompt-repo/deployments/': {
      id: '/workspace/prompt-repo/deployments/'
      path: '/prompt-repo/deployments'
      fullPath: '/workspace/prompt-repo/deployments/'
      preLoaderRoute: typeof WorkspacePromptRepoDeploymentsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/pii-redactor/rules/': {
      id: '/workspace/pii-redactor/rules/'
      path: '/rules'
      fullPath: '/workspace/pii-redactor/rules/'
      preLoaderRoute: typeof WorkspacePiiRedactorRulesIndexRouteImport
      parentRoute: typeof WorkspacePiiRedactorRouteRoute
    }
    '/workspace/pii-redactor/providers/': {
      id: '/workspace/pii-redactor/providers/'
      path: '/providers'
      fullPath: '/workspace/pii-redactor/providers/'
      preLoaderRoute: typeof WorkspacePiiRedactorProvidersIndexRouteImport
      parentRoute: typeof WorkspacePiiRedactorRouteRoute
    }
    '/workspace/logs/mcp-logs/': {
      id: '/workspace/logs/mcp-logs/'
      path: '/mcp-logs'
      fullPath: '/workspace/logs/mcp-logs/'
      preLoaderRoute: typeof WorkspaceLogsMcpLogsIndexRouteImport
      parentRoute: typeof WorkspaceLogsRouteRoute
    }
    '/workspace/logs/dashboard/': {
      id: '/workspace/logs/dashboard/'
      path: '/'
      fullPath: '/workspace/logs/dashboard/'
      preLoaderRoute: typeof WorkspaceLogsDashboardIndexRouteImport
      parentRoute: typeof WorkspaceLogsDashboardRouteRoute
    }
    '/workspace/logs/connectors/': {
      id: '/workspace/logs/connectors/'
      path: '/connectors'
      fullPath: '/workspace/logs/connectors/'
      preLoaderRoute: typeof WorkspaceLogsConnectorsIndexRouteImport
      parentRoute: typeof WorkspaceLogsRouteRoute
    }
    '/workspace/guardrails/providers/': {
      id: '/workspace/guardrails/providers/'
      path: '/providers'
      fullPath: '/workspace/guardrails/providers/'
      preLoaderRoute: typeof WorkspaceGuardrailsProvidersIndexRouteImport
      parentRoute: typeof WorkspaceGuardrailsRouteRoute
    }
    '/workspace/guardrails/configuration/': {
      id: '/workspace/guardrails/configuration/'
      path: '/configuration'
      fullPath: '/workspace/guardrails/configuration/'
      preLoaderRoute: typeof WorkspaceGuardrailsConfigurationIndexRouteImport
      parentRoute: typeof WorkspaceGuardrailsRouteRoute
    }
    '/workspace/governance/virtual-keys/': {
      id: '/workspace/governance/virtual-keys/'
      path: '/virtual-keys'
      fullPath: '/workspace/governance/virtual-keys/'
      preLoaderRoute: typeof WorkspaceGovernanceVirtualKeysIndexRouteImport
      parentRoute: typeof WorkspaceGovernanceRouteRoute
    }
    '/workspace/governance/users/': {
      id: '/workspace/governance/users/'
      path: '/users'
      fullPath: '/workspace/governance/users/'
      preLoaderRoute: typeof WorkspaceGovernanceUsersIndexRouteImport
      parentRoute: typeof WorkspaceGovernanceRouteRoute
    }
    '/workspace/governance/teams/': {
      id: '/workspace/governance/teams/'
      path: '/teams'
      fullPath: '/workspace/governance/teams/'
      preLoaderRoute: typeof WorkspaceGovernanceTeamsIndexRouteImport
      parentRoute: typeof WorkspaceGovernanceRouteRoute
    }
    '/workspace/governance/rbac/': {
      id: '/workspace/governance/rbac/'
      path: '/rbac'
      fullPath: '/workspace/governance/rbac/'
      preLoaderRoute: typeof WorkspaceGovernanceRbacIndexRouteImport
      parentRoute: typeof WorkspaceGovernanceRouteRoute
    }
    '/workspace/governance/customers/': {
      id: '/workspace/governance/customers/'
      path: '/customers'
      fullPath: '/workspace/governance/customers/'
      preLoaderRoute: typeof WorkspaceGovernanceCustomersIndexRouteImport
      parentRoute: typeof WorkspaceGovernanceRouteRoute
    }
    '/workspace/config/security/': {
      id: '/workspace/config/security/'
      path: '/security'
      fullPath: '/workspace/config/security/'
      preLoaderRoute: typeof WorkspaceConfigSecurityIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/config/proxy/': {
      id: '/workspace/config/proxy/'
      path: '/proxy'
      fullPath: '/workspace/config/proxy/'
      preLoaderRoute: typeof WorkspaceConfigProxyIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/config/pricing-config/': {
      id: '/workspace/config/pricing-config/'
      path: '/pricing-config'
      fullPath: '/workspace/config/pricing-config/'
      preLoaderRoute: typeof WorkspaceConfigPricingConfigIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/config/performance-tuning/': {
      id: '/workspace/config/performance-tuning/'
      path: '/performance-tuning'
      fullPath: '/workspace/config/performance-tuning/'
      preLoaderRoute: typeof WorkspaceConfigPerformanceTuningIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/config/observability/': {
      id: '/workspace/config/observability/'
      path: '/observability'
      fullPath: '/workspace/config/observability/'
      preLoaderRoute: typeof WorkspaceConfigObservabilityIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/config/mcp-gateway/': {
      id: '/workspace/config/mcp-gateway/'
      path: '/mcp-gateway'
      fullPath: '/workspace/config/mcp-gateway/'
      preLoaderRoute: typeof WorkspaceConfigMcpGatewayIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/config/logging/': {
      id: '/workspace/config/logging/'
      path: '/logging'
      fullPath: '/workspace/config/logging/'
      preLoaderRoute: typeof WorkspaceConfigLoggingIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/config/large-payload/': {
      id: '/workspace/config/large-payload/'
      path: '/large-payload'
      fullPath: '/workspace/config/large-payload/'
      preLoaderRoute: typeof WorkspaceConfigLargePayloadIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/config/client-settings/': {
      id: '/workspace/config/client-settings/'
      path: '/client-settings'
      fullPath: '/workspace/config/client-settings/'
      preLoaderRoute: typeof WorkspaceConfigClientSettingsIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/config/caching/': {
      id: '/workspace/config/caching/'
      path: '/caching'
      fullPath: '/workspace/config/caching/'
      preLoaderRoute: typeof WorkspaceConfigCachingIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
    '/workspace/config/api-keys/': {
      id: '/workspace/config/api-keys/'
      path: '/api-keys'
      fullPath: '/workspace/config/api-keys/'
      preLoaderRoute: typeof WorkspaceConfigApiKeysIndexRouteImport
      parentRoute: typeof WorkspaceConfigRouteRoute
    }
  }
}

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface PprofRouteRouteChildren {
  PprofIndexRoute: typeof PprofIndexRoute
}

const PprofRouteRouteChildren: PprofRouteRouteChildren = {
  PprofIndexRoute: PprofIndexRoute,
}

const PprofRouteRouteWithChildren = PprofRouteRoute._addFileChildren(
  PprofRouteRouteChildren,
)

interface WorkspaceAdaptiveRoutingRouteRouteChildren {
  WorkspaceAdaptiveRoutingIndexRoute: typeof WorkspaceAdaptiveRoutingIndexRoute
}

const WorkspaceAdaptiveRoutingRouteRouteChildren: WorkspaceAdaptiveRoutingRouteRouteChildren =
  {
    WorkspaceAdaptiveRoutingIndexRoute: WorkspaceAdaptiveRoutingIndexRoute,
  }

const WorkspaceAdaptiveRoutingRouteRouteWithChildren =
  WorkspaceAdaptiveRoutingRouteRoute._addFileChildren(
    WorkspaceAdaptiveRoutingRouteRouteChildren,
  )

interface WorkspaceAuditLogsRouteRouteChildren {
  WorkspaceAuditLogsIndexRoute: typeof WorkspaceAuditLogsIndexRoute
}

const WorkspaceAuditLogsRouteRouteChildren: WorkspaceAuditLogsRouteRouteChildren =
  {
    WorkspaceAuditLogsIndexRoute: WorkspaceAuditLogsIndexRoute,
  }

const WorkspaceAuditLogsRouteRouteWithChildren =
  WorkspaceAuditLogsRouteRoute._addFileChildren(
    WorkspaceAuditLogsRouteRouteChildren,
  )

interface WorkspaceClusterRouteRouteChildren {
  WorkspaceClusterIndexRoute: typeof WorkspaceClusterIndexRoute
}

const WorkspaceClusterRouteRouteChildren: WorkspaceClusterRouteRouteChildren = {
  WorkspaceClusterIndexRoute: WorkspaceClusterIndexRoute,
}

const WorkspaceClusterRouteRouteWithChildren =
  WorkspaceClusterRouteRoute._addFileChildren(
    WorkspaceClusterRouteRouteChildren,
  )

interface WorkspaceConfigRouteRouteChildren {
  WorkspaceConfigIndexRoute: typeof WorkspaceConfigIndexRoute
  WorkspaceConfigApiKeysIndexRoute: typeof WorkspaceConfigApiKeysIndexRoute
  WorkspaceConfigCachingIndexRoute: typeof WorkspaceConfigCachingIndexRoute
  WorkspaceConfigClientSettingsIndexRoute: typeof WorkspaceConfigClientSettingsIndexRoute
  WorkspaceConfigLargePayloadIndexRoute: typeof WorkspaceConfigLargePayloadIndexRoute
  WorkspaceConfigLoggingIndexRoute: typeof WorkspaceConfigLoggingIndexRoute
  WorkspaceConfigMcpGatewayIndexRoute: typeof WorkspaceConfigMcpGatewayIndexRoute
  WorkspaceConfigObservabilityIndexRoute: typeof WorkspaceConfigObservabilityIndexRoute
  WorkspaceConfigPerformanceTuningIndexRoute: typeof WorkspaceConfigPerformanceTuningIndexRoute
  WorkspaceConfigPricingConfigIndexRoute: typeof WorkspaceConfigPricingConfigIndexRoute
  WorkspaceConfigProxyIndexRoute: typeof WorkspaceConfigProxyIndexRoute
  WorkspaceConfigSecurityIndexRoute: typeof WorkspaceConfigSecurityIndexRoute
}

const WorkspaceConfigRouteRouteChildren: WorkspaceConfigRouteRouteChildren = {
  WorkspaceConfigIndexRoute: WorkspaceConfigIndexRoute,
  WorkspaceConfigApiKeysIndexRoute: WorkspaceConfigApiKeysIndexRoute,
  WorkspaceConfigCachingIndexRoute: WorkspaceConfigCachingIndexRoute,
  WorkspaceConfigClientSettingsIndexRoute:
    WorkspaceConfigClientSettingsIndexRoute,
  WorkspaceConfigLargePayloadIndexRoute: WorkspaceConfigLargePayloadIndexRoute,
  WorkspaceConfigLoggingIndexRoute: WorkspaceConfigLoggingIndexRoute,
  WorkspaceConfigMcpGatewayIndexRoute: WorkspaceConfigMcpGatewayIndexRoute,
  WorkspaceConfigObservabilityIndexRoute:
    WorkspaceConfigObservabilityIndexRoute,
  WorkspaceConfigPerformanceTuningIndexRoute:
    WorkspaceConfigPerformanceTuningIndexRoute,
  WorkspaceConfigPricingConfigIndexRoute:
    WorkspaceConfigPricingConfigIndexRoute,
  WorkspaceConfigProxyIndexRoute: WorkspaceConfigProxyIndexRoute,
  WorkspaceConfigSecurityIndexRoute: WorkspaceConfigSecurityIndexRoute,
}

const WorkspaceConfigRouteRouteWithChildren =
  WorkspaceConfigRouteRoute._addFileChildren(WorkspaceConfigRouteRouteChildren)

interface WorkspaceCustomPricingRouteRouteChildren {
  WorkspaceCustomPricingIndexRoute: typeof WorkspaceCustomPricingIndexRoute
}

const WorkspaceCustomPricingRouteRouteChildren: WorkspaceCustomPricingRouteRouteChildren =
  {
    WorkspaceCustomPricingIndexRoute: WorkspaceCustomPricingIndexRoute,
  }

const WorkspaceCustomPricingRouteRouteWithChildren =
  WorkspaceCustomPricingRouteRoute._addFileChildren(
    WorkspaceCustomPricingRouteRouteChildren,
  )

interface WorkspaceDashboardRouteRouteChildren {
  WorkspaceDashboardIndexRoute: typeof WorkspaceDashboardIndexRoute
}

const WorkspaceDashboardRouteRouteChildren: WorkspaceDashboardRouteRouteChildren =
  {
    WorkspaceDashboardIndexRoute: WorkspaceDashboardIndexRoute,
  }

const WorkspaceDashboardRouteRouteWithChildren =
  WorkspaceDashboardRouteRoute._addFileChildren(
    WorkspaceDashboardRouteRouteChildren,
  )

interface WorkspaceGovernanceRouteRouteChildren {
  WorkspaceGovernanceIndexRoute: typeof WorkspaceGovernanceIndexRoute
  WorkspaceGovernanceCustomersIndexRoute: typeof WorkspaceGovernanceCustomersIndexRoute
  WorkspaceGovernanceRbacIndexRoute: typeof WorkspaceGovernanceRbacIndexRoute
  WorkspaceGovernanceTeamsIndexRoute: typeof WorkspaceGovernanceTeamsIndexRoute
  WorkspaceGovernanceUsersIndexRoute: typeof WorkspaceGovernanceUsersIndexRoute
  WorkspaceGovernanceVirtualKeysIndexRoute: typeof WorkspaceGovernanceVirtualKeysIndexRoute
}

const WorkspaceGovernanceRouteRouteChildren: WorkspaceGovernanceRouteRouteChildren =
  {
    WorkspaceGovernanceIndexRoute: WorkspaceGovernanceIndexRoute,
    WorkspaceGovernanceCustomersIndexRoute:
      WorkspaceGovernanceCustomersIndexRoute,
    WorkspaceGovernanceRbacIndexRoute: WorkspaceGovernanceRbacIndexRoute,
    WorkspaceGovernanceTeamsIndexRoute: WorkspaceGovernanceTeamsIndexRoute,
    WorkspaceGovernanceUsersIndexRoute: WorkspaceGovernanceUsersIndexRoute,
    WorkspaceGovernanceVirtualKeysIndexRoute:
      WorkspaceGovernanceVirtualKeysIndexRoute,
  }

const WorkspaceGovernanceRouteRouteWithChildren =
  WorkspaceGovernanceRouteRoute._addFileChildren(
    WorkspaceGovernanceRouteRouteChildren,
  )

interface WorkspaceGuardrailsRouteRouteChildren {
  WorkspaceGuardrailsIndexRoute: typeof WorkspaceGuardrailsIndexRoute
  WorkspaceGuardrailsConfigurationIndexRoute: typeof WorkspaceGuardrailsConfigurationIndexRoute
  WorkspaceGuardrailsProvidersIndexRoute: typeof WorkspaceGuardrailsProvidersIndexRoute
}

const WorkspaceGuardrailsRouteRouteChildren: WorkspaceGuardrailsRouteRouteChildren =
  {
    WorkspaceGuardrailsIndexRoute: WorkspaceGuardrailsIndexRoute,
    WorkspaceGuardrailsConfigurationIndexRoute:
      WorkspaceGuardrailsConfigurationIndexRoute,
    WorkspaceGuardrailsProvidersIndexRoute:
      WorkspaceGuardrailsProvidersIndexRoute,
  }

const WorkspaceGuardrailsRouteRouteWithChildren =
  WorkspaceGuardrailsRouteRoute._addFileChildren(
    WorkspaceGuardrailsRouteRouteChildren,
  )

interface WorkspaceLogsDashboardRouteRouteChildren {
  WorkspaceLogsDashboardIndexRoute: typeof WorkspaceLogsDashboardIndexRoute
}

const WorkspaceLogsDashboardRouteRouteChildren: WorkspaceLogsDashboardRouteRouteChildren =
  {
    WorkspaceLogsDashboardIndexRoute: WorkspaceLogsDashboardIndexRoute,
  }

const WorkspaceLogsDashboardRouteRouteWithChildren =
  WorkspaceLogsDashboardRouteRoute._addFileChildren(
    WorkspaceLogsDashboardRouteRouteChildren,
  )

interface WorkspaceLogsRouteRouteChildren {
  WorkspaceLogsDashboardRouteRoute: typeof WorkspaceLogsDashboardRouteRouteWithChildren
  WorkspaceLogsIndexRoute: typeof WorkspaceLogsIndexRoute
  WorkspaceLogsConnectorsIndexRoute: typeof WorkspaceLogsConnectorsIndexRoute
  WorkspaceLogsMcpLogsIndexRoute: typeof WorkspaceLogsMcpLogsIndexRoute
}

const WorkspaceLogsRouteRouteChildren: WorkspaceLogsRouteRouteChildren = {
  WorkspaceLogsDashboardRouteRoute:
    WorkspaceLogsDashboardRouteRouteWithChildren,
  WorkspaceLogsIndexRoute: WorkspaceLogsIndexRoute,
  WorkspaceLogsConnectorsIndexRoute: WorkspaceLogsConnectorsIndexRoute,
  WorkspaceLogsMcpLogsIndexRoute: WorkspaceLogsMcpLogsIndexRoute,
}

const WorkspaceLogsRouteRouteWithChildren =
  WorkspaceLogsRouteRoute._addFileChildren(WorkspaceLogsRouteRouteChildren)

interface WorkspaceMcpRegistryRouteRouteChildren {
  WorkspaceMcpRegistryIndexRoute: typeof WorkspaceMcpRegistryIndexRoute
}

const WorkspaceMcpRegistryRouteRouteChildren: WorkspaceMcpRegistryRouteRouteChildren =
  {
    WorkspaceMcpRegistryIndexRoute: WorkspaceMcpRegistryIndexRoute,
  }

const WorkspaceMcpRegistryRouteRouteWithChildren =
  WorkspaceMcpRegistryRouteRoute._addFileChildren(
    WorkspaceMcpRegistryRouteRouteChildren,
  )

interface WorkspaceMcpSettingsRouteRouteChildren {
  WorkspaceMcpSettingsIndexRoute: typeof WorkspaceMcpSettingsIndexRoute
}

const WorkspaceMcpSettingsRouteRouteChildren: WorkspaceMcpSettingsRouteRouteChildren =
  {
    WorkspaceMcpSettingsIndexRoute: WorkspaceMcpSettingsIndexRoute,
  }

const WorkspaceMcpSettingsRouteRouteWithChildren =
  WorkspaceMcpSettingsRouteRoute._addFileChildren(
    WorkspaceMcpSettingsRouteRouteChildren,
  )

interface WorkspaceModelLimitsRouteRouteChildren {
  WorkspaceModelLimitsIndexRoute: typeof WorkspaceModelLimitsIndexRoute
}

const WorkspaceModelLimitsRouteRouteChildren: WorkspaceModelLimitsRouteRouteChildren =
  {
    WorkspaceModelLimitsIndexRoute: WorkspaceModelLimitsIndexRoute,
  }

const WorkspaceModelLimitsRouteRouteWithChildren =
  WorkspaceModelLimitsRouteRoute._addFileChildren(
    WorkspaceModelLimitsRouteRouteChildren,
  )

interface WorkspaceObservabilityRouteRouteChildren {
  WorkspaceObservabilityIndexRoute: typeof WorkspaceObservabilityIndexRoute
}

const WorkspaceObservabilityRouteRouteChildren: WorkspaceObservabilityRouteRouteChildren =
  {
    WorkspaceObservabilityIndexRoute: WorkspaceObservabilityIndexRoute,
  }

const WorkspaceObservabilityRouteRouteWithChildren =
  WorkspaceObservabilityRouteRoute._addFileChildren(
    WorkspaceObservabilityRouteRouteChildren,
  )

interface WorkspacePiiRedactorRouteRouteChildren {
  WorkspacePiiRedactorIndexRoute: typeof WorkspacePiiRedactorIndexRoute
  WorkspacePiiRedactorProvidersIndexRoute: typeof WorkspacePiiRedactorProvidersIndexRoute
  WorkspacePiiRedactorRulesIndexRoute: typeof WorkspacePiiRedactorRulesIndexRoute
}

const WorkspacePiiRedactorRouteRouteChildren: WorkspacePiiRedactorRouteRouteChildren =
  {
    WorkspacePiiRedactorIndexRoute: WorkspacePiiRedactorIndexRoute,
    WorkspacePiiRedactorProvidersIndexRoute:
      WorkspacePiiRedactorProvidersIndexRoute,
    WorkspacePiiRedactorRulesIndexRoute: WorkspacePiiRedactorRulesIndexRoute,
  }

const WorkspacePiiRedactorRouteRouteWithChildren =
  WorkspacePiiRedactorRouteRoute._addFileChildren(
    WorkspacePiiRedactorRouteRouteChildren,
  )

interface WorkspacePluginsRouteRouteChildren {
  WorkspacePluginsIndexRoute: typeof WorkspacePluginsIndexRoute
}

const WorkspacePluginsRouteRouteChildren: WorkspacePluginsRouteRouteChildren = {
  WorkspacePluginsIndexRoute: WorkspacePluginsIndexRoute,
}

const WorkspacePluginsRouteRouteWithChildren =
  WorkspacePluginsRouteRoute._addFileChildren(
    WorkspacePluginsRouteRouteChildren,
  )

interface WorkspaceProvidersRouteRouteChildren {
  WorkspaceProvidersIndexRoute: typeof WorkspaceProvidersIndexRoute
  WorkspaceProvidersModelLimitsIndexRoute: typeof WorkspaceProvidersModelLimitsIndexRoute
  WorkspaceProvidersRoutingRulesIndexRoute: typeof WorkspaceProvidersRoutingRulesIndexRoute
}

const WorkspaceProvidersRouteRouteChildren: WorkspaceProvidersRouteRouteChildren =
  {
    WorkspaceProvidersIndexRoute: WorkspaceProvidersIndexRoute,
    WorkspaceProvidersModelLimitsIndexRoute:
      WorkspaceProvidersModelLimitsIndexRoute,
    WorkspaceProvidersRoutingRulesIndexRoute:
      WorkspaceProvidersRoutingRulesIndexRoute,
  }

const WorkspaceProvidersRouteRouteWithChildren =
  WorkspaceProvidersRouteRoute._addFileChildren(
    WorkspaceProvidersRouteRouteChildren,
  )

interface WorkspaceRbacRouteRouteChildren {
  WorkspaceRbacIndexRoute: typeof WorkspaceRbacIndexRoute
}

const WorkspaceRbacRouteRouteChildren: WorkspaceRbacRouteRouteChildren = {
  WorkspaceRbacIndexRoute: WorkspaceRbacIndexRoute,
}

const WorkspaceRbacRouteRouteWithChildren =
  WorkspaceRbacRouteRoute._addFileChildren(WorkspaceRbacRouteRouteChildren)

interface WorkspaceRoutingRulesRouteRouteChildren {
  WorkspaceRoutingRulesIndexRoute: typeof WorkspaceRoutingRulesIndexRoute
}

const WorkspaceRoutingRulesRouteRouteChildren: WorkspaceRoutingRulesRouteRouteChildren =
  {
    WorkspaceRoutingRulesIndexRoute: WorkspaceRoutingRulesIndexRoute,
  }

const WorkspaceRoutingRulesRouteRouteWithChildren =
  WorkspaceRoutingRulesRouteRoute._addFileChildren(
    WorkspaceRoutingRulesRouteRouteChildren,
  )

interface WorkspaceScimRouteRouteChildren {
  WorkspaceScimIndexRoute: typeof WorkspaceScimIndexRoute
}

const WorkspaceScimRouteRouteChildren: WorkspaceScimRouteRouteChildren = {
  WorkspaceScimIndexRoute: WorkspaceScimIndexRoute,
}

const WorkspaceScimRouteRouteWithChildren =
  WorkspaceScimRouteRoute._addFileChildren(WorkspaceScimRouteRouteChildren)

interface WorkspaceVirtualKeysRouteRouteChildren {
  WorkspaceVirtualKeysIndexRoute: typeof WorkspaceVirtualKeysIndexRoute
}

const WorkspaceVirtualKeysRouteRouteChildren: WorkspaceVirtualKeysRouteRouteChildren =
  {
    WorkspaceVirtualKeysIndexRoute: WorkspaceVirtualKeysIndexRoute,
  }

const WorkspaceVirtualKeysRouteRouteWithChildren =
  WorkspaceVirtualKeysRouteRoute._addFileChildren(
    WorkspaceVirtualKeysRouteRouteChildren,
  )

interface WorkspaceRouteRouteChildren {
  WorkspaceAdaptiveRoutingRouteRoute: typeof WorkspaceAdaptiveRoutingRouteRouteWithChildren
  WorkspaceAuditLogsRouteRoute: typeof WorkspaceAuditLogsRouteRouteWithChildren
  WorkspaceClusterRouteRoute: typeof WorkspaceClusterRouteRouteWithChildren
  WorkspaceConfigRouteRoute: typeof WorkspaceConfigRouteRouteWithChildren
  WorkspaceCustomPricingRouteRoute: typeof WorkspaceCustomPricingRouteRouteWithChildren
  WorkspaceDashboardRouteRoute: typeof WorkspaceDashboardRouteRouteWithChildren
  WorkspaceGovernanceRouteRoute: typeof WorkspaceGovernanceRouteRouteWithChildren
  WorkspaceGuardrailsRouteRoute: typeof WorkspaceGuardrailsRouteRouteWithChildren
  WorkspaceLogsRouteRoute: typeof WorkspaceLogsRouteRouteWithChildren
  WorkspaceMcpRegistryRouteRoute: typeof WorkspaceMcpRegistryRouteRouteWithChildren
  WorkspaceMcpSettingsRouteRoute: typeof WorkspaceMcpSettingsRouteRouteWithChildren
  WorkspaceModelLimitsRouteRoute: typeof WorkspaceModelLimitsRouteRouteWithChildren
  WorkspaceObservabilityRouteRoute: typeof WorkspaceObservabilityRouteRouteWithChildren
  WorkspacePiiRedactorRouteRoute: typeof WorkspacePiiRedactorRouteRouteWithChildren
  WorkspacePluginsRouteRoute: typeof WorkspacePluginsRouteRouteWithChildren
  WorkspaceProvidersRouteRoute: typeof WorkspaceProvidersRouteRouteWithChildren
  WorkspaceRbacRouteRoute: typeof WorkspaceRbacRouteRouteWithChildren
  WorkspaceRoutingRulesRouteRoute: typeof WorkspaceRoutingRulesRouteRouteWithChildren
  WorkspaceScimRouteRoute: typeof WorkspaceScimRouteRouteWithChildren
  WorkspaceVirtualKeysRouteRoute: typeof WorkspaceVirtualKeysRouteRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceAlertChannelsIndexRoute: typeof WorkspaceAlertChannelsIndexRoute
  WorkspaceDocsIndexRoute: typeof WorkspaceDocsIndexRoute
  WorkspaceMcpAuthConfigIndexRoute: typeof WorkspaceMcpAuthConfigIndexRoute
  WorkspaceMcpLogsIndexRoute: typeof WorkspaceMcpLogsIndexRoute
  WorkspaceMcpToolGroupsIndexRoute: typeof WorkspaceMcpToolGroupsIndexRoute
  WorkspaceModelCatalogIndexRoute: typeof WorkspaceModelCatalogIndexRoute
  WorkspacePromptRepoDeploymentsIndexRoute: typeof WorkspacePromptRepoDeploymentsIndexRoute
  WorkspacePromptRepoPromptsIndexRoute: typeof WorkspacePromptRepoPromptsIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceAdaptiveRoutingRouteRoute:
    WorkspaceAdaptiveRoutingRouteRouteWithChildren,
  WorkspaceAuditLogsRouteRoute: WorkspaceAuditLogsRouteRouteWithChildren,
  WorkspaceClusterRouteRoute: WorkspaceClusterRouteRouteWithChildren,
  WorkspaceConfigRouteRoute: WorkspaceConfigRouteRouteWithChildren,
  WorkspaceCustomPricingRouteRoute:
    WorkspaceCustomPricingRouteRouteWithChildren,
  WorkspaceDashboardRouteRoute: WorkspaceDashboardRouteRouteWithChildren,
  WorkspaceGovernanceRouteRoute: WorkspaceGovernanceRouteRouteWithChildren,
  WorkspaceGuardrailsRouteRoute: WorkspaceGuardrailsRouteRouteWithChildren,
  WorkspaceLogsRouteRoute: WorkspaceLogsRouteRouteWithChildren,
  WorkspaceMcpRegistryRouteRoute: WorkspaceMcpRegistryRouteRouteWithChildren,
  WorkspaceMcpSettingsRouteRoute: WorkspaceMcpSettingsRouteRouteWithChildren,
  WorkspaceModelLimitsRouteRoute: WorkspaceModelLimitsRouteRouteWithChildren,
  WorkspaceObservabilityRouteRoute:
    WorkspaceObservabilityRouteRouteWithChildren,
  WorkspacePiiRedactorRouteRoute: WorkspacePiiRedactorRouteRouteWithChildren,
  WorkspacePluginsRouteRoute: WorkspacePluginsRouteRouteWithChildren,
  WorkspaceProvidersRouteRoute: WorkspaceProvidersRouteRouteWithChildren,
  WorkspaceRbacRouteRoute: WorkspaceRbacRouteRouteWithChildren,
  WorkspaceRoutingRulesRouteRoute: WorkspaceRoutingRulesRouteRouteWithChildren,
  WorkspaceScimRouteRoute: WorkspaceScimRouteRouteWithChildren,
  WorkspaceVirtualKeysRouteRoute: WorkspaceVirtualKeysRouteRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceAlertChannelsIndexRoute: WorkspaceAlertChannelsIndexRoute,
  WorkspaceDocsIndexRoute: WorkspaceDocsIndexRoute,
  WorkspaceMcpAuthConfigIndexRoute: WorkspaceMcpAuthConfigIndexRoute,
  WorkspaceMcpLogsIndexRoute: WorkspaceMcpLogsIndexRoute,
  WorkspaceMcpToolGroupsIndexRoute: WorkspaceMcpToolGroupsIndexRoute,
  WorkspaceModelCatalogIndexRoute: WorkspaceModelCatalogIndexRoute,
  WorkspacePromptRepoDeploymentsIndexRoute:
    WorkspacePromptRepoDeploymentsIndexRoute,
  WorkspacePromptRepoPromptsIndexRoute: WorkspacePromptRepoPromptsIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  PprofRouteRoute: PprofRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
