{
 "title": "Test Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bifrost_cost_total{provider=\"openai\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(bifrost_success_requests_total{provider=\"openai\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(bifrost_error_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Input Tokens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bifrost_input_tokens_total{provider=\"openai\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Output Tokens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bifrost_output_tokens_total{provider=\"openai\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "First Token Latency",
   "type": "histogram",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "bifrost_stream_first_token_latency_seconds_bucket{provider=\"openai\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inter Token Latency",
   "type": "histogram",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "bifrost_stream_inter_token_latency_seconds_bucket{provider=\"openai\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}