#!/usr/bin/env bash
# ============================================================
# Vault Dev Server Initialization Script
# Seeds test secrets for TC-012 (HashiCorp Vault Integration)
# Run AFTER starting Vault dev server:
#   docker run --cap-add=IPC_LOCK -e VAULT_DEV_ROOT_TOKEN_ID=dev-root \
#     -e VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200 -p 8200:8200 hashicorp/vault:1.15
# ============================================================

set -euo pipefail

VAULT_ADDR="${VAULT_ADDR:-http://localhost:8200}"
VAULT_TOKEN="${VAULT_TOKEN:-dev-root}"

export VAULT_ADDR
export VAULT_TOKEN

echo "==> Waiting for Vault to be ready..."
for i in $(seq 1 30); do
  if vault status > /dev/null 2>&1; then
    echo "    Vault ready!"
    break
  fi
  echo "    Attempt $i/30 — Vault not ready yet, waiting..."
  sleep 2
done

echo ""
echo "==> Enabling KV v2 secrets engine at 'secret/'"
vault secrets enable -path=secret kv-v2 2>/dev/null || echo "    (already enabled)"

echo ""
echo "==> Seeding test secrets..."

# Primary OpenAI key (used by provider-vault in TC-012-001)
vault kv put secret/bifrost/openai \
  api_key="sk-vault-test-openai-key-resolved-abc123" \
  description="Test OpenAI API key stored in Vault"
echo "    ✓ secret/bifrost/openai"

# Anthropic key
vault kv put secret/bifrost/anthropic \
  api_key="ant-vault-test-anthropic-key-resolved-xyz789" \
  description="Test Anthropic API key stored in Vault"
echo "    ✓ secret/bifrost/anthropic"

# Test key for TC-012-007 (rotation test — will be updated)
vault kv put secret/bifrost/rotate-test \
  api_key="sk-old-key-before-rotation" \
  version="v1"
echo "    ✓ secret/bifrost/rotate-test (will be updated in TC-012-007)"

echo ""
echo "==> Enabling AppRole authentication..."
vault auth enable approle 2>/dev/null || echo "    (already enabled)"

# Create a policy for Bifrost
vault policy write bifrost-reader - <<EOF
path "secret/data/bifrost/*" {
  capabilities = ["read", "list"]
}
EOF
echo "    ✓ bifrost-reader policy created"

# Create AppRole for Bifrost
vault write auth/approle/role/bifrost-test \
  token_policies="bifrost-reader" \
  token_ttl="1h" \
  token_max_ttl="4h" \
  secret_id_ttl="24h"
echo "    ✓ bifrost-test AppRole created"

# Get and store role_id + secret_id for TC-012-005
ROLE_ID=$(vault read -field=role_id auth/approle/role/bifrost-test/role-id)
SECRET_ID=$(vault write -field=secret_id -f auth/approle/role/bifrost-test/secret-id)

echo ""
echo "==> AppRole credentials for TC-012-005:"
echo "    role_id:   $ROLE_ID"
echo "    secret_id: $SECRET_ID"

# Save to file for test use
cat > "$(dirname "$0")/vault-approle-creds.json" <<APPCREDS
{
  "role_id": "$ROLE_ID",
  "secret_id": "$SECRET_ID",
  "vault_addr": "$VAULT_ADDR",
  "_note": "Auto-generated by vault-init.sh — do not commit to production"
}
APPCREDS
echo "    Saved to vault/vault-approle-creds.json"

echo ""
echo "==> Vault initialization complete!"
echo ""
echo "Test config for Bifrost:"
echo "  vault_addr:    $VAULT_ADDR"
echo "  vault_token:   $VAULT_TOKEN  (token auth mode)"
echo "  kv_version:    v2"
echo "  mount_path:    secret"
echo ""
echo "Secrets available:"
echo "  vault://secret/bifrost/openai#api_key"
echo "  vault://secret/bifrost/anthropic#api_key"
echo "  vault://secret/bifrost/rotate-test#api_key"
