name: Core Dependency Update

# Triggers when core library is tagged
on:
  push:
    tags:
      - "core/v*"

# Prevent concurrent runs for the same trigger to avoid conflicts
concurrency:
  group: core-dependency-update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Run core provider tests before updating dependencies to ensure compatibility
  core-tests:
    runs-on: ubuntu-latest
    name: Run Core Provider Tests
    
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.1"
      
      # Set up Node.js for running test scripts
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      
      # Install script dependencies
      - name: Install script dependencies
        working-directory: ci/scripts
        run: npm ci
      
      # Run core provider tests (excluding Ollama and SGL)
      - name: Run Core Provider Tests
        env:
          # OpenAI
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
          # Anthropic
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Azure OpenAI
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
          AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
          AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
          
          # AWS Bedrock
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          
          # Cohere
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          
          # Google Vertex AI
          VERTEX_API_KEY: ${{ secrets.VERTEX_API_KEY }}
          VERTEX_PROJECT_ID: ${{ secrets.VERTEX_PROJECT_ID }}
          VERTEX_REGION: ${{ secrets.VERTEX_REGION }}
          VERTEX_CREDENTIALS: ${{ secrets.VERTEX_CREDENTIALS }}
          
          # Mistral AI
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          
          # Groq
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          chmod +x ci/scripts/run-core-tests.mjs
          node ci/scripts/run-core-tests.mjs

  update-dependency:
    needs: core-tests
    runs-on: ubuntu-latest
    permissions:
      contents: write # Need write access to create branches and push changes
      pull-requests: write # Need to create pull requests
    steps:
      # Checkout with full history and tags for version management
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history needed for git tag operations
          fetch-tags: true # Ensure all tags are available
          token: ${{ secrets.GH_TOKEN }} # Personal token for pushing changes

      # Set up Go environment for building and dependency management
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.1"

      # Set up Node.js for running our CI scripts
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Install script dependencies first
      - name: Install script dependencies
        working-directory: ci/scripts
        run: npm ci

      # Configure Git for automated commits
      - name: Configure Git
        working-directory: ci/scripts
        run: node git-operations.mjs configure

      # Extract core version and run the complete pipeline
      - name: Run core dependency update pipeline
        working-directory: ci/scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Extract core version from tag
          CORE_VERSION=$(node extract-version.mjs "${GITHUB_REF}" core version)
          echo "📦 Extracted core version: ${CORE_VERSION}"
          
          # Run the complete core dependency update pipeline
          node run-pipeline.mjs core-dependency-update "${CORE_VERSION}" 